version: 2.1

references:
  node_defaults: &node_defaults
    working_directory: ~/app
    docker:
      - image: cimg/node:22.9.0

jobs:
  checkout_code:
    <<: *node_defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/app
          paths:
            - .

  build:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/app/node_modules
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules

  test_unit:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: npm run test

  test_lint:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: npm run test:lint

  test_types:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run: npm run typecheck

  release:
    <<: *node_defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Release a new version
          command: npx semantic-release

  build_image:
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apk add --no-cache jq
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build application Docker image
          command: |
            docker build -t app -f Dockerfile .
      - deploy:
          name: Push Docker images
          command: |
            docker login ghcr.io -u syroegkin -p${GITHUB_TOKEN}
            docker tag app "ghcr.io/syroegkin/$(jq -r '.name' package.json):$(jq -r '.version' package.json)"
            docker push "ghcr.io/syroegkin/$(jq -r '.name' package.json):$(jq -r '.version' package.json)"
            docker tag app "ghcr.io/syroegkin/$(jq -r '.name' package.json):latest"
            docker push "ghcr.io/syroegkin/$(jq -r '.name' package.json):latest"

workflows:
  test_and_deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - test_unit:
          requires:
            - build
      - test_lint:
          requires:
            - build
      - test_types:
          requires:
            - build
      - release:
          context:
            - semantic-release
          filters:
            branches:
              only:
                - master
                - beta
          requires:
            - test_unit
            - test_lint
            - test_types
      - build_image:
          context:
            - semantic-release
          filters:
            branches:
              only:
                - master
          requires:
            - release
